### ISSUE TITLE
Acceptance tests does not install ginkgo for you anymore

### ISSUE THREAD

**Issue by swetharepakula** [cloudfoundry/cf-acceptance-tests#115]
Cf-acceptance-tests may be broken on a fresh install. By default we try to install ginkgo if it does not currently exist in your path. Before it was able to look into the godeps folder and build it for you, but now since it moved to vender that does not work.

/cc @DanLavine

**Comment by robdimsdale** [comment]
You're probably correct in that this may not work out of the box if `$GOPATH/src/github.com/onsi/ginkgo/ginkgo` doesn't exist.

In switching to the `vendor` directory instead of `Godeps/_workspace` we ran into an issue where `go` will not build things that are not directly under the `$GOPATH` - we resolved this for the errand by symlinking, but we could probably also:

```
go install github.com/cloudfoundry/cf-acceptance-tests/vendor/github.com/onsi/ginkgo/ginkgo
```

This would also allow us to remove the symlink in the cf-acceptance-tests errand

**Comment by robdimsdale** [comment]
@Amit-PivotalLabs do you want to us to make the above change? We could also not make the change and instead document in the README that users should `go get -u github.com/onsi/ginkgo`. Your call

**Comment by Amit-PivotalLabs** [comment]
@robdimsdale let's make the change so the test script install ginkgo for you.

**Comment by Amit-PivotalLabs** [comment]
This appears to be fixed now, closing.
