### ISSUE TITLE
bosh-lite CATs fails spectacularly when `api.bosh-lite.com` is temporarily unreachable

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/cf-acceptance-tests#189]
Like most open source teams, we run CATs as our final CI step to make sure nothing is broken.

Our CI pipeline is a Christmas color splatter because of a reoccurring error.

```
[2017-03-14 23:56:31.91 (UTC)]> cf api api.bosh-lite.com --skip-ssl-validation 
Setting api endpoint to api.bosh-lite.com...
Request error: Get https://api.bosh-lite.com/v2/info: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED
```

When this happens early on in CATs, most of the subsequent tests will fail.

I'd like to request that some retry logic be added for setup. Whether this happens in `cf` CLI or in the `ginkgo` tests should be up to some discussion.

Or maybe we can resolve the `*.bosh-lite.com` issue with something more resilient.

**Comment by jtarchie** [comment]
This is bosh lite running on GCP.

**Comment by dsabeti** [comment]
Hey @jtarchie. Thanks for opening this issue. It seems like a lot of people have been experiencing various network flakes on bosh-lite. There are two things to thing about here:
1) CATs and/or the CLI should be more robust to network flakiness.
2) We should dig in and figure out why networking has seemed to deteriorate on bosh-lite.

I'm actually not sure if the issue is DNS -- the error is `dial tcp: i/o timeout` which typically indicates a lower-level issue with networking than with DNS. Also, `bosh-lite.com` is served by Route53, which I think has a pretty good SLA.

@anEXPer, let's get a story written to capture this problem and get a pair to try to work on it soon.

**Comment by dsabeti** [comment]
Hey @jtarchie, apologies for letting this issue slide. Are you still seeing these `dial tcp: i/o timeout` errors on bosh-lite?

**Comment by anEXPer** [comment]
@dsabeti, pretty sure we addressed this months ago with a slightly increased dial timeout env var for the CF CLI.
