### ISSUE TITLE
Missing coverage in CATS

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/cf-acceptance-tests#209]
Looks like CATS is missing a test to ensure that an app with more memory than is available on diego should fail to stage. This test is in fact part of [WATS](https://github.com/cloudfoundry/wats/blob/master/src/wats/dats_staging_failure_test.go#L17-L45) the windows acceptance tests. The suggested test would have caught a bug that was introduced in the CC. The bug caused staging tasks not to inherit the application's memory limits and instead use a lower memory limit. 

See [this capi tracker story](https://www.pivotaltracker.com/story/show/146125789) for more info. Diego jobs that failed as a result of this bug can be found [here](https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/ketchup-run-wats/builds/290) and [here](https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/ketchup-run-wats/builds/289)

**Comment by dsabeti** [comment]
Hi @jvshahid. This coverage should definitely be included in CATs. I also suspect that, once it's there, it can be removed from WATs. I'll prioritize this story soon.

**Comment by jvshahid** [comment]
great, thanks!

**Comment by dsabeti** [comment]
@zrob @Gerg Since the test described here mostly covers Cloud Controller logic, I'm wondering if this is something that could be tested in the CC unit tests.

For more context, WATs has a test that pushes an app and requests some very large amount of memory such that Diego can't accommodate the app an any cell. The test asserts that the app fails to stage. Instead of testing this in CATs, and simulating the failure condition by actually pushing an app and asking for so much memory, is there a way to mock out the failure response from Diego and unit testing this instead?

**Comment by Gerg** [comment]
After the original bug, we created this chore to add coverage: https://www.pivotaltracker.com/story/show/146488657

There may be a CC-only test that we can write. Sending and respecting the quotas might be an interesting integration to test in the CATs, but it would be much easier if we found a way to inspect the actual memory/disk available from inside the app's container.

**Comment by dsabeti** [comment]
@Gerg I'd like to use this as a chance to see if can right a lower level test instead of a CATs test. If, after we've written a CC-only test, we still feel like we're missing coverage, RelInt can add a test to CATs to get this coverage. But, in general, I'm trying to reduce the bloat in CATs and find other places to test edge/error cases.

**Comment by aashah** [comment]
Hey @dsabeti,

We agree with what you've said about this being a CC-only concern and have written more unit-level integration tests to capture this missing coverage.

Closing this issue!
