### ISSUE TITLE
CF-ACCAPTANCE-TEST fails because of false ENV variable check

### ISSUE THREAD

**Issue by stjimmy88** [cloudfoundry/cf-acceptance-tests#231]
https://github.com/cloudfoundry/cf-acceptance-tests/blob/0fe0df171c9bd33c48f68962dcb39ae626a1be93/apps/default_environment_variables.go#L178

**Comment by stjimmy88** [comment]
Supposed Environment Variable is `CF_INSTANCE_PORT` but CAT test tries to match regexp as `<string>: TASK.*CF_INSTANCE_PORTS=.*`

**Comment by dsabeti** [comment]
Hey @stjimmy88. It looks like [the test asserts on both](https://github.com/cloudfoundry/cf-acceptance-tests/blob/0fe0df171c9bd33c48f68962dcb39ae626a1be93/apps/default_environment_variables.go#L177-L178). As far as I can tell, both environment variables are valid environment variables. The Diego Cell [adds that environment variable explicitly](https://github.com/cloudfoundry/executor/blob/28327329289df7329b6a83b63aabdb707ab830ef/depot/steps/run_step.go#L325).

It seems more likely that the log line was lost due to some kind of flakiness. Do you see this failure persistently, or is it intermittent?

**Comment by stjimmy88** [comment]
Hi @dsabeti , it looks intermittent. Issue disappeared by itself. Thanks for you time.
