### ISSUE TITLE
compile fails cats_suite_test.go:140:20

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/cf-acceptance-tests#564]
I tried another CATS run today, but it failed with the following compile error:

+ echo 'Using Ginkgo Version 1.16.5'
+ ginkgo -nodes=3 --noisySkippings=false --flakeAttempts=2 '--skip=fails with insufficient resources' '--skip=uses a buildpack from a git url' '--skip=Downloads the correct user specified git buildpack'

Failed to compile cf-acceptance-tests:

# github.com/cloudfoundry/cf-acceptance-tests_test [github.com/cloudfoundry/cf-acceptance-tests.test]
./cats_suite_test.go:140:20: cannot use helpers.NewJUnitReporter(Config, "CATS") (value of type *"github.com/onsi/ginkgo/v2/reporters".JUnitReporter) as type ginkgo.Reporter in argument to append:
	*"github.com/onsi/ginkgo/v2/reporters".JUnitReporter does not implement ginkgo.Reporter (wrong type for AfterSuiteDidRun method)
		have AfterSuiteDidRun(_ *"github.com/onsi/ginkgo/v2/types".DeprecatedSetupSummary)
		want AfterSuiteDidRun(setupSummary *"github.com/onsi/ginkgo/types".SetupSummary)

For now I pinned back to the last successful run on commit 4764122d95f2d1285cbc4c5d03b0862a414f1bec (tag v7.5.0)

**Comment by ctlong** [comment]
Hi @metskem! This error is likely due to the recent bump to ginkgo v2 in [cf-test-helpers](https://github.com/cloudfoundry/cf-test-helpers). I don't expect anything to work until this repository is upgraded to use ginkgo v2 as well (see this [PR](https://github.com/cloudfoundry/cf-test-helpers)).

I would not recommend using the `develop` branch of CATs for testing in production as we make no promises about breaking that on a commit-by-commit basis. If you want to be on the cutting edge then at least the `release-candidate` branch has passed through CI successfully.

**Comment by metskem** [comment]
We will switch to main branch.
Thanks for the quick update.
