### ISSUE TITLE
Dotnet core buildpack tests can fail with 504 gateway timeout

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cf-acceptance-tests#627]
The dotnet core buildpack tests have just been updated with PR: https://github.com/cloudfoundry/cf-acceptance-tests/pull/610
This PR introduces a large amount of application resources (many .dll files). When pushing the test app, the request `POST /v3/resource_matches` can fail on AWS environments with a HTTP 504 gateway timeout. The default idle timeout is 60s which may not be enough to finish the upload. Workaround is to increase the timeout to 300s.

Can you reduce the application resources somehow? I'm not familiar with dotnet so I don't know which options we have here.

**Comment by mariash** [comment]
@jochenehret thank you for reporting this issue. We didn't catch it on our environments, probably our default timeouts are large enough. The reason the asset is too large is because we vendored all the dependencies (by publishing an app). The next step from vendored would be a pre-compiled asset but that would not exercise dotnet core buildpack and would use binary buildpack. We are going to look into ways to reduce the size of the asset. For now I suggest to increase the gateway timeout.

**Comment by jochenehret** [comment]
Tests are running fine, so let's keep the increased lb timeout. Closing this issue.
