### ISSUE TITLE
Issue with customised router status page and new readiness_heathcheck tests

### ISSUE THREAD

**Issue by corlettb** [cloudfoundry/cf-acceptance-tests#929]
During our recent cloud foundry upgrade we had an issue with the acceptance-tests:

```
Expected
      <string>: << INSERT LONG FANCY HTML WITH LOTS OF LOVELY FORMATTING >>
      <string>: 404 Not Found
  In [It] at: /tmp/build/f541ec31/src/github.com/cloudfoundry/cf-acceptance-tests/apps/readiness_healthcheck.go:72 @ 09/13/23 10:44:40.031
```

It looks like [this check](https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/apps/readiness_healthcheck.go#L72) has a hardcoded check for '404 Not Found', however we are using a custom router error page.

Our router error pages ends up with something like:

```
...
404</span><h1 class="xxxxxxxx">Not Found
...
```

So it does not match the ContainSubstring check.

I've worked around this by adding a:

```
<meta name="for-acceptance-tests" content="{{ .Status }} {{ .StatusText }}" />
```

 into the error page.

Maybe it's worth changing this test to just check if a 404 status is returned?

**Comment by ctlong** [comment]
@corlettb thanks for reporting this problem!

Unfortunately, checking if a 404 status is returned is rather difficult due to the complex web of helpers used throughout CATs.

However, we can instead change the checks to look for simply `404`, like [some Windows tests](https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/windows/routing.go#L57).

**Comment by ctlong** [comment]
Should be fixed in https://github.com/cloudfoundry/cf-acceptance-tests/releases/tag/v15.2.0
